name: "Debug Artifact"
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Build"
        run: pnpm build

      - name: "Upload artifact for inspection"
        uses: actions/upload-artifact@v4
        with:
          name: debug-package-artifact
          path: |
            dist
            .bin/cli.worker.js
            package.json
            LICENSE
            README.md
            jsr.json
            lib

  inspect:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: debug-package-artifact

      - name: "DEBUG: Inspect artifact contents"
        run: |
          echo "--- Files in current directory ---"
          ls -laR
          echo "--- Content of package.json ---"
          cat package.json
