name: "Test Deno"

on:
  workflow_dispatch:

jobs:
  test:
    name: "Test Deno"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: "Install Deno"
        run: deno install --allow-scripts=npm:dprint

      - name: "Run Sample"
        run: deno run --allow-read scripts/sample.deno.js
